In [1]:
import numpy as np
# Configure the Jupyter notebook to output multiple lines of the output of the cell
from IPython.core.interactiveshell import InteractiveShell  
InteractiveShell.ast_node_interactivity = "all"

## Array Creation

In [2]:
a = np.arange(15)
a.shape

a = a.reshape(3,5)
a.shape
a.ndim
a.dtype.name
a.itemsize
a.size
type(a)

(15,)

(3, 5)

2

'int64'

8

15

numpy.ndarray

For ones, zeros, empty methods; the default data type is float64

In [3]:
a = np.array([2,3,4], dtype=complex)
a

b =np.zeros((3,4))
b
c = np.ones((2,3,4))
c
d = np.empty((2,3))
d
d.dtype


array([2.+0.j, 3.+0.j, 4.+0.j])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

array([[4.63738182e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

dtype('float64')

## Printing Arrays
The axis is printed from left to right.

Second-to-last is printed from top to bottom.

The rest are also printed from top to bottom, each slice separated from the next by an empty line.

In [4]:
print(30*"=")

a = np.arange(6)                    # 1d array

print("a:",30*"-",'\n',a)

b = np.arange(12).reshape(4, 3)                  # 2d array

print("b:",30*"-",'\n',b)

c = np.arange(24).reshape(2, 3,4)                  # 2d array

print("c:",30*"-",'\n',c,"\n",30*"=")


a: ------------------------------ 
 [0 1 2 3 4 5]
b: ------------------------------ 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
c: ------------------------------ 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 


## Basic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with result.

In [5]:
a = np.array([20,30,40,50])
b = np.arange(4)
b
c= a-b
c
b**2
10*np.sin(a)

a<35


array([0, 1, 2, 3])

array([20, 29, 38, 47])

array([0, 1, 4, 9])

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

array([ True,  True, False, False])

Matrix product can be performed using @ operator (in python>=3.5) or the dot function or method.

In [6]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
A*B
A@B
A.dot(B)
np.dot(A,B)

array([[2, 0],
       [0, 4]])

array([[5, 4],
       [3, 4]])

array([[5, 4],
       [3, 4]])

array([[5, 4],
       [3, 4]])

Operators like +=, -=, *= act in place and modify the existing array instead of creating a new one and populating it with the result.

In [7]:
rg = np.random.default_rng(1)
a = np.ones((2,3),dtype=int)
b = rg.random((2,3))
a *=3 # a is automatically converted to float type (upcasted)
a 

b += a # b is not automatically converted to integer type
b


array([[3, 3, 3],
       [3, 3, 3]])

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [8]:
a = np.ones(3,dtype=np.int32)
b = np.linspace(0,np.pi,3)
b.dtype.name

c= a+b
c
c.dtype.name

d = np.exp(c*1j)
d

d.dtype.name


'float64'

array([1.        , 2.57079633, 4.14159265])

'float64'

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

'complex128'

### Unary operations

In [9]:
# Unary operations are implemented as methods
a = rg.random((2,3))
a 
a.sum()
a.min()
a.max()

# By specifying axis parameter you can apply an operation along the specified axis of an array
b =np.arange(12).reshape(3,4)
b

b.sum(axis=0) # Sum of each column

b.min(axis=1) # Min of each row. Returned as a row vector not a column vector 

b.cumsum(axis=1) # Cumilative sum along each row

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

3.1057109529998157

0.027559113243068367

0.8277025938204418

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([12, 15, 18, 21])

array([0, 4, 8])

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## Universal Functions
all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where ...

In [10]:
B = np.arange(3)
B 
np.exp(B)
np.sqrt(B)
C = np.array([2.,-1.,4.])
np.add(B,C)


array([0, 1, 2])

array([1.        , 2.71828183, 7.3890561 ])

array([0.        , 1.        , 1.41421356])

array([2., 0., 6.])

## Indexing, Slicing, Iterating

In [11]:
a = np.arange(10)**3
a 
a[2]
a[2:5]
a[:6:2]=100 # From start to position 6, set every second element 100, Equivalent to a[0:6:2]
a
a[::-1] # Reversed a
a
for i in a:
    print(i**(1/3.))

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

8

array([ 8, 27, 64])

array([100,   1, 100,  27, 100, 125, 216, 343, 512, 729])

array([729, 512, 343, 216, 125, 100,  27, 100,   1, 100])

array([100,   1, 100,  27, 100, 125, 216, 343, 512, 729])

4.641588833612778
1.0
4.641588833612778
3.0
4.641588833612778
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [12]:
# Multidimensional arrays can have one index per axis. These indices are given in a tuple seperated by commas:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

b[2,3]
b[0:5,1]
b[:,1]
b[1:3,:]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

23

array([ 1, 11, 21, 31, 41])

array([ 1, 11, 21, 31, 41])

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [13]:
b[-1] # the last row. Equivalent to b[-1,:]
# The dots ... represent as many colons as needed to produce a complete indexing tuple.
# x[1,2, ...] = x[1,2,:,:,:]
# x[..., 3] = x[:,:,:,:,3]
# x[4,...,5,:] = x[4, :,:,5,:]
c = np.array([[[0,1,2],
                [10,12,13]],
                [[100,101,102],
                [110,112,113]]])
c.shape
c[1,...]
c[...,2] # same as c[:,:,2]

array([40, 41, 42, 43])

(2, 2, 3)

array([[100, 101, 102],
       [110, 112, 113]])

array([[  2,  13],
       [102, 113]])

In [14]:
# Iterating over multidimensional arrays is done with respect to the first axis
b
b[1,:]
for row in b:
    print(row)

for element in b.flat:  # flatt attribute which is a n iterator over all the elements of the array
    print(element)



array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

array([10, 11, 12, 13])

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## Shape Manipulation

In [15]:
# An array has a shape given by the number of elements along each axis
a = np.floor(10*rg.random((3,4)))
a
a.shape

a.ravel() # Returns the array, flattened
a.reshape(6,2) # returns the array with a modified shape
a.T             # returns the array transposed
## THESE DO NOT MODIFY THE ORIGINAL ARRAY.
a.T.shape
a.shape


array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

(3, 4)

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

(4, 3)

(3, 4)

The order of the elements in the array resulting from ravel is normally "C-style", that is, the rightmost index "changes the fastest", so the element after a[0,0] is a[0,1]. If the array is reshaped to some other shape again the array is treated as "C-Style". NumPy normally creates arrays stored in this order, so ravel will usually not need to copy its argiment, but if the array was made by taking slices f another arrays or created with unusual options it may need to be copied. The functions ravel and reshape can als be instructed, using an optional argumetn, to use FORTRAN-style arrays, in which the leftmost index changes the fastest.

In [16]:
# The reshape function returns its argument with a modified shape, 
# whereas the ndarray.resize method modifies the array itself.
a = np.arange(12)
a
a.resize((2,6))
a
a.reshape((3,-1)) # If a dimension is given as -1 in a reshaping operation, 
# the other dimensions are automatically calculated.


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Stacking together different arrays    

In [20]:
a = np.floor(10*rg.random((2,2)))
a
b = np.floor(10*rg.random((2,2)))
b 
np.vstack((a,b))
np.hstack((a,b))



array([[1., 8.],
       [6., 7.]])

array([[1., 8.],
       [1., 0.]])

array([[1., 8.],
       [6., 7.],
       [1., 8.],
       [1., 0.]])

array([[1., 8., 1., 8.],
       [6., 7., 1., 0.]])

In [39]:
from numpy import newaxis
a = np.floor(10*rg.random((2,2)))
a
b = np.floor(10*rg.random((2,2)))
b 
np.column_stack((a,b)) # column stack stacks 1D arrays (vectors) into 2D array.
# It is equivalent to hstack only for 2D arrays

a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b))
np.hstack((a,b))
print("\nvvvv View 'a' as a 2D column vector vvvv")
print("a:", a[:,newaxis])
print("b:",b[:,newaxis])
print("Column Stack:", np.column_stack((a[:,newaxis],b[:,newaxis])))
print("HStack:",np.hstack((a[:,newaxis],b[:,newaxis])))

np.r_[1:4,0,4,7]
np.c_

array([[0., 3.],
       [9., 2.]])

array([[8., 6.],
       [8., 6.]])

array([[0., 3., 8., 6.],
       [9., 2., 8., 6.]])

array([[4., 3.],
       [2., 8.]])

array([4., 2., 3., 8.])


vvvv View 'a' as a 2D column vector vvvv
a: [[4.]
 [2.]]
b: [[3.]
 [8.]]
Column Stack: [[4. 3.]
 [2. 8.]]
HStack: [[4. 3.]
 [2. 8.]]


array([1, 2, 3, 0, 4, 7])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 9 and the array at index 1 has size 1