In [2]:
import numpy as np


In [20]:
# Create two random tensors

rng = np.random.default_rng(12345)
A =  rng.random((2,3,4))
B =  rng.random((2,3,4))
a = np.arange(24).reshape(2,3,4)
b = np.arange(-12,12,1).reshape(2,3,4)
print("shape(A)=",A.shape,",\nA:\n",A,'\n',"shape(B)=",B.shape,",\nB:\n",B)
print("shape(a)=",a.shape,",\na=\n",a,'\n',"shape(b)=",b.shape,"\nb=\n",b)

shape(A)= (2, 3, 4) ,
A:
 [[[0.22733602 0.31675834 0.79736546 0.67625467]
  [0.39110955 0.33281393 0.59830875 0.18673419]
  [0.67275604 0.94180287 0.24824571 0.94888115]]

 [[0.66723745 0.09589794 0.44183967 0.88647992]
  [0.6974535  0.32647286 0.73392816 0.22013496]
  [0.08159457 0.1598956  0.34010018 0.46519315]]] 
 shape(B)= (2, 3, 4) ,
B:
 [[[0.26642103 0.8157764  0.19329439 0.12946908]
  [0.09166475 0.59856801 0.8547419  0.60162124]
  [0.93198836 0.72478136 0.86055132 0.9293378 ]]

 [[0.54618601 0.93767296 0.49498794 0.27377318]
  [0.45177871 0.66503892 0.33089093 0.90345401]
  [0.25707418 0.33982834 0.2588534  0.35544648]]]
shape(a)= (2, 3, 4) ,
a=
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 
 shape(b)= (2, 3, 4) 
b=
 [[[-12 -11 -10  -9]
  [ -8  -7  -6  -5]
  [ -4  -3  -2  -1]]

 [[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]]


In [33]:
# Inner product of two tensors 
# The tensors are vectorized first, then inner product of two vectors are taken
print("a.b =", np.vdot(a,b))
print("A.B =", np.vdot(A,B))

# Frobenius norm of a tensor
print("||A||_F = ", np.linalg.norm(A))
print("sqrt(vdot(A,A))=",np.sqrt(np.vdot(A,A)) )

# Trace of a matrix
print("trace(A(1,:,:)=", np.trace(A[1,...]))
# SVD of a matrix
X = A[1,...]
u, s ,vh = np.linalg.svd(X)
print("\n\nX= ", X)
print(10*'-',"SVD",10*'-')
print("U=",u,"\n\nS=",s,"\n\nVh=",vh,'\n\n',15*'-')

# Nuclear norm of a matrix
print("\n",10*"--","Nuclear Norm",10*"--")
print("||A(1,:,:)||_nuc=",np.linalg.norm(A[1,...],'nuc'))
print("Sum of singular values of A(1,:,:) =",np.sum(np.linalg.svd(A[1,...],True,False)))
print("trace{ A(1,:,:) A(1,:,:)*}=",np.trace(np.sqrt( A[1,...].T @ A[1,...] ) ))
print(20*"---")



a.b = 1012
A.B = 6.042918677486567
||A||_F =  2.680149846723642
sqrt(vdot(A,A))= 2.680149846723642
trace(A(1,:,:)= 1.3338105021251898


X=  [[0.66723745 0.09589794 0.44183967 0.88647992]
 [0.6974535  0.32647286 0.73392816 0.22013496]
 [0.08159457 0.1598956  0.34010018 0.46519315]]
---------- SVD ----------
U= [[ 0.71491502  0.54690689 -0.4356482 ]
 [ 0.61697958 -0.78658124  0.0250231 ]
 [ 0.3289874   0.28667544  0.89976913]] 

S= [1.61350732 0.55279829 0.26629366] 

Vh= [[ 0.57897242  0.19993067  0.5457584   0.57180978]
 [-0.2899718  -0.28674482 -0.43080921  0.80504483]
 [-0.75034484  0.4140569   0.49528085  0.14225466]
 [ 0.13300344  0.84045346 -0.52081481  0.06855656]] 

 ---------------

 -------------------- Nuclear Norm --------------------
||A(1,:,:)||_nuc= 2.432599261473079
Sum of singular values of A(1,:,:) = 2.432599261473079
trace{ A(1,:,:) A(1,:,:)*}= 3.291370830471304
------------------------------------------------------------


In [39]:
# Vector outer product
print(10*'--',"Vector outer product",10*'--')
x = np.arange(5.)
y = np.arange(5.)-2.5
print("x=",x,'\ny=',y)
V = np.outer(x,y)
print("V=",V)
print(30*'--','\n')

# np.tensordot


-------------------- Vector outer product --------------------
x= [0. 1. 2. 3. 4.] 
y= [-2.5 -1.5 -0.5  0.5  1.5]
V= [[ -0.   -0.   -0.    0.    0. ]
 [ -2.5  -1.5  -0.5   0.5   1.5]
 [ -5.   -3.   -1.    1.    3. ]
 [ -7.5  -4.5  -1.5   1.5   4.5]
 [-10.   -6.   -2.    2.    6. ]]
------------------------------------------------------------ 



In [ ]:
# Tensor-matrix multiplication



In [1]:
# Linear operator and adjoint


In [ ]:
# Homogenous tensor array


In [ ]:
# Tensor rank

# Tensor n-rank